USE cumbia_peruana;

SELECT * FROM grupos;

--- INGRESO DE GRUPOS FUNDADORES DE LA CUMBIA PERUANA ---

INSERT INTO grupos (nombre_grupo, id_director)
VALUES
('Los Destellos', 1),
('Juaneco y su Combo', 2),
('Los Diablos Rojos', 3),
('Manzanita y su Conjunto', 3),
('Los Beltons de Ayacucho', 4),
('Los Beta 5', 5),
('Los Walkers de Huánuco', 6),
('Los Quantos de Ica', 7),
('Los Girasoles', 8),
('Los Chavales', 8),
('Los Darlings de Huánuco', 22),
('Los Casmeños', 1),
('Los Gatos Blancos', 12),
('Los Sanders de Ñaña', 13),
('Los Blue Kings de Ñaña', 9),
('Costa Azul de Ñaña', 10),
('Los Ecos', 11),
('Los Diablos Rojos', 12),
('Los Mirlos', 14),
('Los Pakines', 15),
('Los Yungas', 16),
('Los Almendros', 17),
('El Monje Loco', 3),
('Los Popeyes', NULL),
('Los Australes de Pachacamac', 18),
('Ranil y su Conjunto', 19),
('Marcial y sus Estrellas', 20),
('Los Benfords', 21),
('Los Fantásticos de Chimbote', 22),
('Los Huermayanos', 23),
('Los Darlings de Huánuco', 22),
('Los Timbales de Huacho', 24),
('Los Roger de Barranca', 25),
('Los Chicos Malos de Barranca', NULL),
('Pintura Fresca de Paramonga', 26),
('Los Orientales de Paramonga', 27),
('Los Yelton de Paramonga', 28),
('Los Orientales de Paramonga', 29),
('Los Dinámicos de Paramonga', 30),
('Los Átomos de Paramonga', 31),
('Los Palmer de Paramonga', NULL),
('Los Vagos de Paramonga', 32),
('Los Diferentes de Paramonga', 33),
('Los Jelwees de Tingo María', 34),
('Los Rangers de Tingo María', 35),
('Grupo Siglo XX de Rioja', 36),
('Los Wemblers de Iquitos', 37),
('Sonido 2000 de Tarapoto', 38),
('Grupo 2000 de Tarapoto', 38),
('Los Silvers de Iquitos', 39),
('Los Trionix de Rioja', 40);


