USE cumbia_peruana;

SELECT * FROM grupos;

-- Insertar Grupos (ordenados por cantidad de audios - mayor a menor)
INSERT INTO grupos (nombre_grupo, id_director)
VALUES
('Los Destellos', 1),
('Los Diablos Rojos', 2),
('Los Mirlos', 3),
('Los Ecos', 4),
('Los Yungas', 5),
('Juaneco y su Combo', 6),
('La Nueva Crema', 7),
('Grupo Guinda', 8),
('Los Shapis', 9),
('Ranil y su Conjunto', 10),
('Cuarteto Continental', 11),
('Grupo Celeste', 12),
('Grupo Karicia', 13),
('Los Chipis', 14),
('Los Invasores de Progreso', 15),
('Los Dexter''s de Uchiza', 16),
('Grupo Maravilla', 17),
('Los Beta 5', 18),
('Grupo Alegría', 19),
('Los Walker''s de Huanuco', 20),
('Los Tigres de Tarapoto', 21),
('Cielo Gris', 22),
('El Super Grupo', 23),
('Cuarteto Universal', 24),
('Los Sander''s de Ñaña', 25),
('Manzanita y su Conjunto', 26),
('Los Ovnis', 27),
('Pintura Roja', 28),
('Sonido 2000 de Tarapoto', 29),
('Grupo Genesis', 30),
('La Mermelada', 31),
('Chacal y sus Estrellas', 32),
('Los Felcas', 33),
('Grupo Sonido Verde de Moyobamba', 34),
('Armonia 10', 35),
('Grupo Halley', 24),
('Los Titanes', 36),
('Los Pakines', 37),
('Los Ilusionistas', 38),
('Agua Marina', 39),
('Grupo Imaginación', 40),
('Los Universales', 41),
('Grupo Naranja', 42),
('Los Girasoles', 43),
('Grupo Melodía', 44),
('Los Orientales de Paramonga', 45),
('Los Virtuosos de la Salsa', 46),
('Los Orientales de Víctor', 47),
('Los Wembler''s de Iquitos', 48),
('Grupo Fiesta', 49),
('Los Astros de Uchiza', 50),
('Los Belton''s', 51),
('El Combo Palacio', 46),
('Los Gitanos del Rimac', 52),
('Grupo Markahuasi', 53),
('Grupo Paraiso de Chincha', 54),
('Los Diamantes de Huancayo', 55),
('Los Grekos del Rimac', 56),
('Los Wankas', 57),
('Los Solitarios', 58),
('Los Super Amigos', 59),
('Los Tigres de Pamplona Alta', 2),
('El Medio Grupo', 60),
('Grupo Atlantic de San Martín', 61),
('Grupo Somos', 62),
('Los Cariñosos', NULL),
('Los Timpanos', 63),
('Grupo Verano', 64),
('Los Galax', 65),
('Grupo Amapola', 66),
('Grupo Andaluz', 67),
('Grupo Mantaro', 68),
('Los Doberman''s de Huancayo', 69),
('Los Topacios', 70),
('Los Blue Kings de Ñaña', 71),
('Los Cerezos', 72),
('Los Zingaros', 73),
('El Nuevo Grupo', 74),
('Grupo Belen', 75),
('Grupo Centeno', 76),
('Los Bellking''s de Piura', 77),
('Los Bio Chips', 14),
('Nube Gris', 78),
('Los Almendros', 79),
('Grupo Néctar', 80),
('Grupo San Lázaro', 81),
('Grupo Santa Fe', 62),
('Los Feos', 82),
('Grupo Fantasma', NULL),
('Los Yabar Junior', 83),
('Grupo Corazón del Cusco', 84),
('Grupo Hawaii Quinto', 85),
('Los Dandy''s', 86),
('Los Ratones', NULL),
('Grupo Punto 5', 87),
('Grupo Rosado', NULL),
('Grupo Siglo XX de Rioja', 88),
('Las Manos Cruzadas', 89),
('Los Darling''s de Huánuco', NULL),
('Los Hijos del Sol', 90),
('Costa Azul de Ñaña', 91),
('Grupo Arco Iris de Huancayo', 92),
('Grupo Aroma de Huarochirí', 93),
('Grupo Kiwi Show', 75),
('Los Canarios', NULL),
('Los Casmeños', 1),
('Los Dinámicos', 28),
('Los Leones', 94),
('Los Ranger''s de Tingo María', 95),
('Oro Negro', 11),
('Grupo Miramar', 96),
('Los Ekos de Yurimaguas', 97),
('Los Fascinantes', 98),
('Los Quantos de Ica', 99),
('Agrupacion 2000 de Chiclayo', 100),
('El Sexteto Cumbianbero', 101),
('Grupo Armonia', 102),
('Grupo Azul', 103),
('Grupo Kariño', 104),
('Grupo San Juan', 105),
('Grupo Solar de Eslabón', 106),
('Grupo Trebol', 107),
('Los Alamos', 108),
('Los Avileños', NULL),
('Los Blackies', 43),
('Los Cantaritos de Oro', 109),
('Los Caramelos de Aucayacu', 110),
('Los Chavales', 43),
('Los Condores', 111),
('Los Eclipses', 112),
('Los Mensajeros de Ica', 113),
('Los Muky''s', 114),
('Los Pekines', NULL),
('Los Reales de San Martin', 115),
('Los Silver''s de Iquitos', 116),
('Grupo Alfa de Progreso', NULL),
('Grupo Magico', 117),
('Grupo Sentimiento', 118),
('Los Bucaneros', 119),
('Los Petroleros', 120),
('Los Yenny''s de Sion', 121),
('Cocodrilo y su Combo', 122),
('El Gran Cuarteto', 123),
('Grupo Hidalgo', 124),
('Grupo Karavanha', 125),
('Los Atomos de Paramonga', 126),
('Los Bambinos de Oro', 127),
('Los Nilos', 128),
('Manuel Mantilla y Orquesta', 117),
('Ray Cuestas', 129),
('Cuarteto Imbatible', 24),
('Grupo Flash', 130),
('Grupo Santo Domingo', 131),
('Los Radiantes de Mala', 132),
('Grupo Acuarela de Piñonate', 133),
('Grupo Arkho Iris', 134),
('Grupo Bengala', 135),
('Grupo Ceniza', 136),
('Grupo Lyra', NULL),
('Grupo Victoria', 137),
('La Orquesta de Freddy Roland', 138),
('La Super Crema', 139),
('La Trombanda', 140),
('Los Andaluces del Rimac', 141),
('Los Brillantes de Lince', 142),
('Los Caminantes', 143),
('Los Happy Shaver''s', 67),
('Los Seibos', 144),
('Los Universales del Rimac', 145),
('Los Virtuosos de la Cumbia', 46),
('Los Yelwis de Huaraz', 146),
('Cuarteto Amazonico', 147),
('El Mejor Grupo', NULL),
('Grupo Paraiso', 148),
('Grupo Santa Martha', 149),
('Grupo Sargento Pimienta', 150),
('Grupo Super Amistad', 151),
('Julio Mau y su Cuarteto', 152),
('Los Estelares', 41),
('Los Naranjos', 153),
('Los Principes', 49),
('Los Royal''s de Pucallpa', 154),
('Grupo Araña', 155),
('Grupo Brisa', 156),
('Grupo Frenesi', 157),
('Grupo Gran Fruto', 158),
('Grupo Paraiso de Lima', 9),
('Grupo Primavera', 159),
('Grupo Safari', NULL),
('Grupo Santa Cruz', 160),
('Grupo Venus', 117),
('La Constelacion', 4),
('La Maffia', 161),
('La Nueva Ilusión', 125),
('La Nueva Sombra', 162),
('La Super Serie de Uchiza', 163),
('Los Amautas de Huancayo', NULL),
('Los Angeles', 164),
('Los Autenticos Cheveres de Chimbote', 165),
('Los Dinámicos de Paramonga', 166),
('Los Esenciales', 167),
('Los Fervis', 168),
('Los Jelwees', 169),
('Los Piraguas de Cerro de Pasco', 170),
('Los Tropicholos', 171),
('Manuel Mantilla y su Conjunto', 117),
('Grupo Esmeralda de Lima', 172),
('Grupo Flamenco', 173),
('La Familia Santa María', NULL),
('La Séptima Región de Pucallpa', NULL),
('Los Cheveres de Chimbote', 174),
('Los Elegantes', 79),
('Los Gatos Blancos', 2),
('Los Grillos', 175),
('Los Parker', 176),
('Los Peregrinos', 177),
('Los Soncossapa', 178),
('Conjunto Luz Roja', 179),
('Estrella Azul', 22),
('Grupo Acuario', 180),
('Grupo Alma Corazon y Vida', 119),
('Grupo Alta Tensión de Cañete', 181),
('Grupo Amistad', 133),
('Grupo Celestial de Huancayo', 182),
('Grupo Corazón 2', 183),
('Grupo Frontera', 184),
('Grupo Granizo', 185),
('Grupo Menta', 186),
('Grupo Nieve', 187),
('Grupo Pintura Fresca de Paramonga', 188),
('Grupo Semilla', 189),
('Grupo Sensación', 190),
('Grupo Shyshako', 191),
('Grupo Super Star', 192),
('Grupo Tauro', 193),
('Grupo Vanidad', 194),
('Grupo Viento', 195),
('Grupo Zereza', 196),
('La Mezcla', 197),
('La Nueva Fresa', 125),
('La Sangre Joven', 198),
('Los 5 Amigos', 2),
('Los Australes', NULL),
('Los Cachorros', 199),
('Los Caleños', NULL),
('Los Cheveres de Huancayo', 200),
('Los Colegiales', NULL),
('Los Crisoles', NULL),
('Los Fantasticos', 201),
('Los Gatos', NULL),
('Los Grecos', 202),
('Los Iranios', 203),
('Los Kokis', 204),
('Los Provincianos', 205),
('Los Saturnos', 206),
('Los Titanic''s', NULL),
('Los Vagos de Paramonga', 207),
('Los Walas de Huancayo', 208),
('Los Winter''s', 209),
('Los Zafiros', 210),
('Los Zeta''s', 211),
('Pepito Quechua', 212),
('Piraña y sus Autenticos', 213),
('Grupo Amanecer', 214),
('Grupo Amistad de Cerro de Pasco', 215),
('Grupo Fruko Celeste', NULL),
('Grupo Marfil', 213),
('Grupo Palo Santo', NULL),
('La Sombra De Ica', 216),
('Los Caribeños de Chimbote', NULL),
('Los Cisnes de Iquitos', 217),
('Los Claveles de Pucallpa', 218),
('Los Diferentes de Paramonga', NULL),
('Los Escarabajos', NULL),
('Los Henrys', 219),
('Los Imperiales de Laredo', NULL),
('Los Lasser''s de Jauja', 220),
('Los Mirtos', NULL),
('Los Mochileros', NULL),
('Los Raffos', 221),
('Los Rayos', 222),
('Los Standar de Trujillo', 223),
('Los Timbales', 224),
('Armonia 6', 42),
('Armonia 7 de Chiclayo', NULL),
('Conjunto Anabacoa', NULL),
('Conjunto Nueva Galaxia', 225),
('El Clan 6', 226),
('El Monje Loco', 26),
('El Nuevo Grupo de Ica', NULL),
('Grupo Acido', 227),
('Grupo Acuarela', NULL),
('Grupo Aguas Verdes', NULL),
('Grupo Alta Tensión', 228),
('Grupo Amapola 2', 196),
('Grupo Amistad de Pichanaki', 229),
('Grupo Amor de Tarapoto', 230),
('Grupo América', 17),
('Grupo Arco Iris', 231),
('Grupo Arizona', 232),
('Grupo Bahia Blanca', 233),
('Grupo Banana Show', NULL),
('Grupo Brisas Azules', 112),
('Grupo Canela', NULL),
('Grupo Capricho', 234),
('Grupo Capuli', 7),
('Grupo Cariño', 235),
('Grupo Cascabel', 236),
('Grupo Cebada', 120),
('Grupo Celestial', NULL),
('Grupo Cereza', 237),
('Grupo Cereza de Ica', 99),
('Grupo Cielo Azul', 238),
('Grupo Colores', NULL),
('Grupo Constelación', NULL),
('Grupo Corazón', 239),
('Grupo Corazón de Huanchaco', NULL),
('Grupo Cordillera', 240),
('Grupo Costa Verde', 241),
('Grupo Cruz de Amor', NULL),
('Grupo Delirio de Ayacucho', 242),
('Grupo Diamante', NULL),
('Grupo Dorado', 243),
('Grupo Escorpio', 244),
('Grupo Esmeralda', 186),
('Grupo Espejismo', NULL),
('Grupo Espejo', 245),
('Grupo Estelar', NULL),
('Grupo Estrella', 31),
('Grupo Fantasia de Monsefú', 246),
('Grupo Flecha Verde', 247),
('Grupo Flor Silvers', 248),
('Grupo Fresa de Juvenil de Tarapoto', NULL),
('Grupo Fruta', 26),
('Grupo Fruto Celeste', 7),
('Grupo Fuego Azul', 249),
('Grupo Fuego Azul de Independencia', 250),
('Grupo Gamma', NULL),
('Grupo Genesis del Cusco', 251),
('Grupo Gente Extraña', NULL),
('Grupo Granada', 252),
('Grupo Ilusion', 31),
('Grupo Ilusión de Lima', 253),
('Grupo Imperial', 254),
('Grupo Inspiracion', 255),
('Grupo Invierno', 112),
('Grupo Kanelita', 149),
('Grupo Karamelo', 256),
('Grupo Kiwi', 31),
('Grupo Lince', 257),
('Grupo Macondo', 258),
('Grupo Manantial', NULL),
('Grupo Maravilla de Lima', NULL),
('Grupo Marbella', 259),
('Grupo Melocoton', NULL),
('Grupo Melon', 260),
('Grupo Mescalina', 261),
('Grupo Mida', 262),
('Grupo Milagro', 263),
('Grupo Moderno', 264),
('Grupo Morado', 265),
('Grupo Nieve Blanca', 266),
('Grupo Noche', NULL),
('Grupo Nuevo Horizonte', 267),
('Grupo Néctar de San Juan', 31),
('Grupo Paloma', 268),
('Grupo Pañuelito', 254),
('Grupo Pintura Fresca', NULL),
('Grupo Praxis de Pucallpa', 269),
('Grupo Remolino', 25),
('Grupo Revelacion', 270),
('Grupo Sabor', NULL),
('Grupo San Antonio', 271),
('Grupo San Luis', 272),
('Grupo Santa Clara', 273),
('Grupo Santa Cruz de Huancayo', 274),
('Grupo Selva', NULL),
('Grupo Sensación de La Oroya', 275),
('Grupo Shambaris', 221),
('Grupo Sombra Blanca', 69),
('Grupo Son de Oro', NULL),
('Grupo Super Arizona', 232),
('Grupo Super Revelación', 276),
('Grupo Tabacko de Ica', 277),
('Grupo Tabu', 278),
('Grupo Tentación', NULL),
('Grupo Tete', NULL),
('Grupo Uno', NULL),
('Grupo Vanidad 2', 279),
('Grupo VI Dimensión', NULL),
('Grupo Vibración', 280),
('Grupo Yambu', 255),
('Grupo Yogui', 281),
('Grupo Zafari', NULL),
('Grupo Éxito de Huarochiri', NULL),
('Huiro y su Conjunto', NULL),
('La Brigada Roja', 209),
('La Fruna', 282),
('La Gota Dulce', 283),
('La Gran Familia de Chimbote', NULL),
('La Gran Familia de Naranjillo', NULL),
('La Miel', 112),
('La Nueva Constelación', NULL),
('La Reunión', 284),
('La Super Fresa', NULL),
('La Super Mezcla', 120),
('La Super Vida', 285),
('Las Perlas', 286),
('Los 4 Gatos', NULL),
('Los Aguilas', NULL),
('Los Andaluces', 287),
('Los Andinos', 288),
('Los Archies', NULL),
('Los Astronautas', NULL),
('Los Audaces', 289),
('Los Benfords', 290),
('Los Caneitos', NULL),
('Los Caribeños', 291),
('Los Casacas Rojas', NULL),
('Los Cascabeles', 292),
('Los Celih''s', 293),
('Los Chicoques', NULL),
('Los Chicos Malos', NULL),
('Los Chilotes', NULL),
('Los Claveles', 294),
('Los Cristales', 295),
('Los Delfines', 94),
('Los Deliciosos', NULL),
('Los Delta 2', 296),
('Los Demonios', NULL),
('Los Denkys', 297),
('Los Denver''s', NULL),
('Los Ekos', NULL),
('Los Exorcistas', 298),
('Los Extraños', 42),
('Los Fender''s', 299),
('Los Figuers', 300),
('Los Floreales', 301),
('Los Gigantes', 302),
('Los Gradioles', 303),
('Los Habaneros', NULL),
('Los Hijos del Rey', 260),
('Los Huermayanos', 304),
('Los Imanes de Chincha', 305),
('Los Inkas', 306),
('Los Inquietos del Rimac', 177),
('Los Jhari''s de Ñaña', 307),
('Los Kappys', 112),
('Los Kapuñay', NULL),
('Los Kelkas', NULL),
('Los Kelton''s', 14),
('Los Kuimber''s', NULL),
('Los Lander''s', 23),
('Los Lechuceros', 308),
('Los Lobos', NULL),
('Los Luceros', NULL),
('Los Luceros de Chincha', 309),
('Los Magnificos', 310),
('Los Mangos de Jauja', 311),
('Los Michigan', NULL),
('Los Milenkos', 312),
('Los Mircos', NULL),
('Los Misteriosos', NULL),
('Los Monjes', 161),
('Los Morris', NULL),
('Los Nativos', 46),
('Los Naylamp', 313),
('Los Norlys', 314),
('Los Opalos', 296),
('Los Paladines', 315),
('Los Palmer''s de Paramonga', 316),
('Los Palmeños de Huacho', 317),
('Los Partons', 318),
('Los Peta 5', NULL),
('Los Pibes', 319),
('Los Poker''s', NULL),
('Los Popeyes', NULL),
('Los Primos', 320),
('Los Ranger''s de Barranca', 321),
('Los Ribereños', 322),
('Los Rogers', 323),
('Los Saltamontes', NULL),
('Los Sentimentales', NULL),
('Los Simoney', 324),
('Los Sobrinos', 325),
('Los Sonnys', 326),
('Los Super Cheveres de Chimbote', 128),
('Los Super Comandos', 132),
('Los Tantos', NULL),
('Los Tigres', NULL),
('Los Trionix', 327),
('Los Tropicales', NULL),
('Los Trotamundo', NULL),
('Los Tunches de Iquitos', 116),
('Los Tíos Titos', 328),
('Los Vagabundos', NULL),
('Los Vientos Latinos', 329),
('Los Wafer''s', 330),
('Los Welkers', NULL),
('Los Yawar''s', 331),
('Los Yeltons', 332),
('Los Zenith', 333),
('Los Zodiac', 334),
('Lucho Nygro y sus Kikos', 116),
('Maravilla', 335),
('Mañuco y sus Estrellas', 62),
('Palo Blanco', NULL),
('Pañuelito y su Grupo', 336),
('Pedrito y su Grupo', NULL),
('Telefono Publico', NULL),
('Tito Perez y sus Estrellas', 337),
('Wilfredo Mendoza y su Grupo', 338),
('Augusto Lucho y sus Satelites', 339),
('Chacalón y su Nuevo Grupo', 7),
('El Clan 5', NULL),
('Grupo 2000 de Tarapoto', 29),
('Grupo Alma Tropical', 340),
('Grupo Anis', 167),
('Grupo Arizona 2000', 341),
('Grupo Audaz', NULL),
('Grupo Caiman', NULL),
('Grupo Crema Batida', NULL),
('Grupo Granizo Show', 342),
('Grupo Impacto', NULL),
('Grupo Impakto', 343),
('Grupo Junin', 344),
('Grupo Karisma de Chimbote', NULL),
('Grupo L.B Huancayo', NULL),
('Grupo Pagano', NULL),
('Grupo Pura Dinamita', NULL),
('Grupo Reflejos', NULL),
('Grupo Rosado Luz', NULL),
('Grupo Sabor 2', NULL),
('Grupo Santanita', NULL),
('Grupo Siglo XXI', NULL),
('Grupo Sol y Mar', NULL),
('Grupo Sonido 7', NULL),
('Grupo Sugar', NULL),
('Grupo Tabaco', NULL),
('Grupo Toronja', NULL),
('La Nueva Generacion', 345),
('La Nueva Inspiración', NULL),
('Los Acuarios', 31),
('Los Ander''s', NULL),
('Los Caribeños 2', NULL),
('Los Chupaca', NULL),
('Los Claveles 2', 218),
('Los Cristales de Huancayo', 346),
('Los Dandy''s de Villa María', NULL),
('Los Dember''s de Canta', 347),
('Los Detalles', NULL),
('Los Diablos', NULL),
('Los Diablos del Norte', NULL),
('Los Diferentes Kennedys', NULL),
('Los Escorpiones', NULL),
('Los Fabulosos', 348),
('Los Fenix', NULL),
('Los Fugitivoz', NULL),
('Los Génesis del Cusco', 349),
('Los Hermanos Calvay', NULL),
('Los Hilton''s del Cuzco', NULL),
('Los Kubaney', NULL),
('Los Luren''s de Ica', 350),
('Los Makakos', NULL),
('Los Memphis de Loreto', NULL),
('Los Mirasoles', NULL),
('Los Nardos', NULL),
('Los Padrinos', NULL),
('Los Pankins', 351),
('Los Playboy', NULL),
('Los Tellos', NULL),
('Los Thermis de San Martín', NULL),
('Los Zheros', 352),
('Paco Zambrano y sus Ratones', NULL),
('Tony Marín', 357),
('Tony Marín y Los Tierra Roja', 357),
('Grupo 5', 358),
('Grupo Paraiso de Lizardo Paolo', 359),
('Eusebio y su Banjo', 360),
('V Revelación de Jaén', NULL),
('Variado', NULL);

