USE cumbia_peruana;

SELECT * FROM grupos;

--- INGRESO DE GRUPOS FUNDADORES DE LA CUMBIA PERUANA ---

INSERT INTO grupos (nombre_grupo, director)
VALUES 
('Los Destellos', 'Enrique Delgado Montes'), ('Juaneco y su Combo', 'Juan Wong Paredes'), ('Manzanita y su Conjunto', 'Juan Berardo Hernández Sánchez'),
('Los Beltons de Ayacucho', 'Américo Vilcatoma Aranda'), ('Los Beta 5', 'Nelson Canevello'), ('Los Walkers de Huánuco', 'Rogelio Velásquez'), 
('Los Quantos de Ica', 'Enrique Canales Carbajo'), ('Los Girasoles', 'Félix Martínez Romero'), ('Los Chavales', 'Felix Martínez Romero'),
('Los Darlings de Huánuco', 'Juan Nájera'), ('Los Casmeños', 'Enrique Delgado Montes'), ('Los Gatos Blancos', 'Marino Valencia Garay'),
('Los Sanders de Ñaña', 'Fernando Arias'), ('Los Blue Kings de Ñaña', 'Prospero Alva'), ('Costa Azul de Ñaña', 'Abrahám Sánchez'),
('Los Ecos', 'Edilberto Cuestas Chacón'), ('Los Diablos Rojos', 'Marino Valencia Garay'), ('Los Mirlos', 'Jorge Rodríguez Grández'),
('Los Pakines', 'Alejandro Torres Liza'), ('Los Yungas', 'Homero Casahuamán Marín'), ('Los Almendros', 'Héctor Bustamante Gomez'),
('El Monje Loco', 'Juan Berardo Hernández Sánchez'), ('Los Popeyes', ''), ('Los Australes de Pachacamac', 'Alejandro Arias Chacón'),
('Ranil y su Conjunto', 'Raúl Llerena Vásquez'), ('Marcial y sus Estrellas', 'Marcial Arevalo'), ('Los Benfords', 'Carlos Salvatierra'),
('Los Fantásticos de Chimbote', 'Jorge Esquivel Zambrano'), ('Los Huermayanos', 'Juan García Salazar'), ('Los Darlings de Huánuco', 'Juan Nájera'),
('Los Timbales de Huacho', 'Carlos Moreno'), ('Los Roger de Barranca', 'Isaac Sánchez Gonzáles'), ('Los Chicos Malos de Barranca', ''),
('Pintura Fresca de Paramonga', 'Luis Guevara'), ('Los Orientales de Paramonga', 'Víctor Ramírez Raymundo'), ('Los Yelton de Paramonga', 'Gilberto Torres'),
('Los Orientales de Paramonga', 'Maximiliano Chávez Saavedra'), ('Los Dinámicos de Paramonga', 'Teofilo Moreno'), ('Los Átomos de Paramonga', 'Juan Robles'), 
('Los Palmer de Paramonga', ''), ('Los Vagos de Paramonga', 'Nestor Flores'), ('Los Diferentes de Paramonga', 'Luis Alberto Zuamarán'),
('Los Jelwees de Tingo María', 'Francisco Vela'), ('Los Rangers de Tingo María', 'Luis Seijas Peña'), ('Grupo Siglo XX de Rioja', 'Pedro Rojas'), 
('Los Wemblers de Iquitos', 'Salomón Sánchez Saavedra'), ('Sonido 2000 de Tarapoto', 'Tulio Trigoso Reátegui'), ('Grupo 2000 de Tarapoto', 'Tulio Trigoso Reátegui'),
('Los Silvers de Iquitos', 'Luis Nigro Sánchez'), ('Los Trionix de Rioja', 'Arturo Garate Salva'), ('Los Diferentes Kennedys', 'Geney Sifuentes Arbildo'),
('Los Tigres de Tarapoto', 'Efrén García Viena'), ('Séptima Región de Pucallpa', 'Eugenio Wong'), ('Tony Marin y Los Tierra Roja', 'Marco Antonio Reátegui'), 
('Los Dexters de Uchiza', 'Emerson Ruíz Mosquera'),  ('Los Escorpiones de Tarapoto', 'Tulio Trigoso Reátegui'), ('Los Reales de San Martín', 'Jorge Franco Prado'), 
('Sonido Verde de Moyobamba', 'Leonardo Vela Rodríguez'), ('Los Invasores de Progreso', 'Ernesto Diestro Herrera'), ('Fresa Juvenil de Tarapoto', 'Dalmace Ríos Rúiz'),
('Los Astros de Uchiza', 'Ronald Ferreyra'), ('Los Cisnes de Iquitos', 'Ygor López Ríos'), ('Los Claveles de Pucallpa', 'Mauro García Pastor'),
('Los Ekos de Yurimaguas', 'Vicente Gonzáles'), ('Variado', 'Alberto Maraví Chombo'), ('Variado', 'Juan Campos Muñoz'), 
('Los Titanes', 'José Manuel de La Cruz'), ('Los Zíngaros', 'Oscar Carbajal Zárate'), ('Chacal y sus Estrellas', 'Alfonso Escalante Quispe'), 
('Grupo Celeste', 'Víctor Casahuamán Bendezú'), ('El Super Grupo', 'Lener Muñoz Reyes'), ('Cielo Gris', 'Teodoro Arellano Fernández'),
('Los Andaluces', 'Humberto Recoba'), ('Grupo Néctar', 'José Luis Carballo'), ('Los Cerezos del Rimac', 'Jorge Nolasco'),
('Los Galax', 'Abel Flores Ramírez'), ('Los Gitanos del Rimac', 'Rolando Vega Carranza'), ('Los Dinámicos', 'Alejandro Zárate Espinoza'),
('Grupo Kiwi Show', 'Juan Chávez Salazar'), ('Grupo Kiwi', 'Lázaro Machuca'), ('Los Happys Shavers', 'Segundo Guillermo Esqueche'), 
('Los Radiantes de Mala', 'Orlando Corpus Barrantes'), ('Grupo Brisa', 'Manuel Cajavilca'), ('Los Hijos del Sol', 'Ángel Anibal Rosado'),
('Los Yabar Junior', 'Zenón Antonio Yabar Díaz'), ('El Nuevo Grupo', 'Julio Risco'), ('Grupo Santa Fe', 'Juan Manuel de La Cruz Ore'),
('Grupo Amapola', 'Jorge Calatayud Olivares'), ('Los Crisoles', 'Anotnio Baldeón Sosa'), ('Grupo Ceniza', 'Enrique Araujo'), 
('Grupo Zereza', 'Jorge Calatayu Olivares'), ('Grupo Guinda', 'Carlos Morales Sánchez'), ('Grupo Maravilla', 'Jorge Chávez Malaver'), 
('Grupo Fiesta', 'Francisco Lema Vásquez'), ('Los Felcas', 'Luis Florentino León Pariasca'), ('Grupo Centeno', 'Carlos Ramírez Centeno'), 
('Grupo Moderno', 'Fernando Limo'), ('Grupo Néctar', 'Antonio Baldeón Sosa'), ('Los Ilusionistas', 'Walter León'), 
('Grupo Bengala', 'Félix Sánchez Ponce'), ('Grupo Amistad', 'Víctor Chumpitaz Dupuy'), ('Grupo América', 'Jorge Chávez Malaver'), 
('Alma, Corazón y Vida', 'Juan Rebaza Cárdenas'), ('Grupo Naranja', 'Pedro Gregorio López'), ('Grupo Primavera', 'Agustin Flores'), 
('Grupo Sensación', 'Horacio Gomez Aragón'), ('Grupo Venus', 'Manuel Mantilla Paredes'), ('Grupo Tabú', 'Antonio Bazurto'), 
('La Constelación', 'Edilberto Cuestas Chacón'), ('La Nuevo Fresa', 'Javier Silva Humeres'), ('La Nueva Ilusión', 'Javier Silva Humeres'), 
('Cocodrilo y su Combo', 'Dionisio Quispe'), ('Grupo Ilusión', 'Hector Chacón'), ('Grupo Estelar', ''), ('El Mejor Grupo', 'José Luis Carballo'), 
('Grupo Karavanha', 'Javier Silva Humeres'), ('Grupo Inspiración', 'Manuel Jesús Llanos'), ('Grupo Yambú', 'Manuel Jesús Llanos'), 
('Grupo Lyra', 'Alberto Maraví Chombo'), ('Grupo Melón', 'Anibal Aliaga'), ('Grupo Primavera', 'Agustín Flores'), 
('Grupo Sabor', 'Víctor Galindo Daza'), ('Grupo Yogui', 'Juan Cahuama Valenzuela'), ('La Nueva Inspiración', 'Enrique Balarezo'), 
('La Super Vida', 'Jorge Ramírez'), ('Los Ángeles', 'Mad Trujillo'), ('Los Dandys', 'Héctor Farfán Canales'), 
('Los Elegantes', 'Héctor Bustamante Gomez'), ('Los Estelares', 'Alfonso Alejandro Morán Sirumbal'), ('Los Fervis', 'Filiberto Vivas'), 
('Los Figuers de Arequipa', 'Henry Figueroa'), ('Los Floriales', 'Alfredo Durand García'), ('Los Magnificos', 'Carlos Palomino'), 
('Los Naranjos', 'César Alvarado B.'), ('Los Opalos', 'Fernando Pacheco Serrano'), ('Los Super Amigos', 'Luis Ríos'), 
('Los Universales del Rimac', 'Juan Alarcón Malvaceda'), ('Manuel Mantilla y su Conjunto', 'Manuel Mantilla Paredes'), ('Grupo San Lázaro', 'Lázaro Machuca'), 
('Grupo Melodía', 'Juan Arana Zumaeta'), ('Grupo Karicia', 'Víctor Carrasco Tineo'), ('Los Shapis', 'Jaime Moreyra Mercado'),  
('Los Ovnis', 'Jorge Chambergo Porta'), ('Grupo Andaluz', 'Segundo Guillermo Esqueche'), ('Los Chipis', 'Federico Alberto Mauri Almonacid'), 
('Grupo Imaginación', 'Abelardo Gutiérrez Alanya'), ('Grupo Belén', 'Juan Chávez Salazar'), ('Grupo Victoria', 'Javier Ramos Choque Silva'), 
('Grupo Esmeralda', 'Carlos Barrios A.'), ('Grupo Gran Fruto', 'Gonzalo Chávez'), ('Grupo Paraiso', 'Venturo Moreira M.'), 
('Grupo Santo Domingo', 'Guillermo Ruíz Barahena'), ('Grupo Tabacko de Ica', 'Orlando Laopa'), ('La Miel', 'Julio Barzola D.'), 
('Los Bio Chips', 'Federico Alberto Mauri Almonacid'), ('Los Cheveres', 'Jesús Meza'), ('Los Delfines', 'Romulo Navarro Meza'), 
('Los Kappys', 'Julio Barzola D.'), ('Los Lassers de Jauja', 'Luis López Torres'), ('Los Piraguas de Cerro de Pasco', 'Crisanto Espinoza'), 
('Los Zetas', 'Ernesto Pomayala'), ('Grupo Alegría', 'Augusto Bernardillo Gutiérrez'), ('Grupo Génesis', 'Josue Jurado Zurita'),
('La Mermelada', 'José Luis Carballo'), ('La Nueva Crema', 'Lorenzo Palacios Quispe'), ('Los Jharis de Ñaña', 'Teodoro Laura Amao'),
('Grupo Santa Cruz', 'Fortunato Calderón'), ('La Maffia', 'Raúl Ríos Guevara'), ('Grupo Arkho Iris de Huacho', 'Carlos Urtecho'),
('El Medio Grupo', 'Saúl Casahuamán Fuertes'), ('Grupo Banana Show', 'Cristobal Gonzáles B.'), ('Grupo Flor Silvers', 'George Závaleta'),
('Grupo Frenesí', 'Hildebrando Bejarano Díaz'), ('Grupo Fuego Azul', 'Americo Quicaña'), ('Grupo Corazón del Cusco', 'Efraín Ochoa'),
('Grupo Cebada', 'Ricardo Valles'), ('Grupo Tentación', 'Javier Azaña Pelaez'), ('Grupo Violeta', 'Marcelo Aguirre'),
('Grupo Granizo Show', 'Jorge Oliver Bernable'), ('Grupo Hidalgo', 'Roberto Suasnabar'), ('Grupo Menta', 'Arturo Velásquez Reynoso'),
('Grupo Nuevo Horizonte', 'José Escalante Quispe'), ('Shishako y sus Muchachos', 'Esteban Aguilar'), ('Grupo Sombra Blanca', 'Alfonso Cordoba'),
('Grupo Super Amistad', 'Pascual Mattos'), ('Grupo Super Arizona', 'Mariano Aliaga Peña'), ('Grupo Super Revelación', 'Ricardo Córdova Cardenas'),
('La Brigada Roja', 'Iván Quispe Sayritupac'), ('Los Winters', 'Iván Quispe Sayritupac'), ('La Super Crema', 'Rubén Jara'),
('Los Esenciales', 'Alberto Amorós'), ('Los Fascinantes de Chosica', 'Moises Cruz Medina'), ('Los Gradioles', 'Adrián Flores Huarachi'),
('Los Kokis', 'Jorge Durand Tovar'), ('Los Seibos', 'Hernán Rodríguez H.'), ('Los Topacios', 'Jesús Oswaldo Ortega Andrade'),
('Los Wafers', 'Felix Vargas'), ('Los Petroleros', 'Ricardo Valles'), ('Los Grekos del Rimac', 'Miguel Ordinola Castillo'),
('Cuarteto Continental', 'Alberto Maraví Chombo'), ('Cuarteto Amazónico', 'Teddy Navarro'), ('Cuarteto Universal', 'Juan Campos Muñoz'), 
('Los Universales', 'Alfonso Alejandro Morán Sirumbal'), ('Pintura Roja', 'Alejandro Zárate Espinoza'), ('Los Sonnys', 'Eloy Ureta'),
('Grupo Halley', 'Juan Campos Muñoz'), ('Grupo Kariño', 'Juan Campos Muñoz'),('Los Nilos', 'Nilo Juan Segura Obregón'), 
('Los Virtuosos de la Cumbia', 'Oscar Sánchez Noriega'), ('Nube Gris', 'José María Yzazaga'), ('Los Blackies', 'Felix Martínez Romero'), 
('Los Bellkings de Piura', 'Aurelio Bayona Quiroga'), ('Grupo Miramar', 'Oscar Hidalgo Vargas'), ('Grupo Atlantic de San Martín', 'Willy Alvarado Martínez'), 
('Armonia 10', 'Juan Lozada Naquiche'), ('Agua Marina', 'Manuel Quiroga Querevalú'), ('Los Yennys', 'Tony Vásquez'), 
('Grupo 5 de Monsefú', 'Elmer Yaipén Uypan'), ('Grupo Fantasia de Monsefú', 'Ricardo Reyes Salazar'), ('Los Cantaritos de Oro', 'Eddy Ayala Pingo'), 
('Los Bucaneros', 'Alberto Maraví Chombo'), ('Los Cariñosos', 'Alberto Maraví Chombo'), ('Grupo Paraiso', 'Lizardo Paolo'), 
('Grupo Paraiso', 'Ricardo Portal'), ('Grupo Amistad de Cerro de Pasco', 'Zósimo Ramírez'), ('Grupo Lyra', 'Alberto Maraví Chombo'),
('Hawaii Quinto', 'Nesito Palomino Pedrosoca'), ('Grupo Remolino', 'Fernando Arias'), ('Grupo Aroma de Huarochirí', 'Edgar Carlos V.'),
('Grupo Flash de Aucayacu', 'Kioshi Simamoto Tuesta'), ('Las Manos Cruzadas', 'Hugo Soto Ponce'), ('Los Leones', 'Romulo Navarro Meza'),
('Los Norlys de La Oroya', 'José López'), ('Los Virtuosos de la Salsa', 'Oscar Sánchez Noriega'), ('Oro Negro', 'Alberto Maraví Chombo'),
('Wilfredo Mendoza y su Grupo', 'Wilfredo Mendoza'), ('Grupo Amanecer', 'Narciso Quispe Huasco'), ('Cielo Azul', 'Tito Aybar C.'),
('Flor Silvers de Iquitos', 'George Závaleta'), ('Grupo Semilla', 'Carlos Cheng'), ('Los Andinos de Huaraz', 'Daniel Mogollón. B'),
('Los Deliciosos', 'José María Yzazaga'), ('Los Yelwis de Huaraz', 'Gerardo Jaimes Soto'), ('Grupo Azúcar de Paramonga', 'Erik Mata Lliuya'),
('El Nuevo Grupo de Ica', 'Manuel Canela'), ('Grupo Acuario', 'Carlos Godoy'), ('La Miel', 'Julio Barzola'), 
('Los Oriundos de Ayacucho', 'Alejandro Agustín Cáceres Perea'), ('Los Piraguas de Cerro de Pasco', 'Crisanto Espinoza S.'),
('Grupo Fama de La Oroya', 'Juvencio Navarro G.'), ('Grupo Karacas', 'José Ramón Asin'), ('Grupo Mazamorra', 'José Ninapaitán Huayta'),
('Los Millonarios', 'Silvio Quispe C.'), ('Los Rayos', 'Máximo Camacho Ruiz'), ('Eusebio y su Banjo', 'Eusebio Pérez Campojo'), 
('El Combo Palacio', 'Alberto Maravi Chombo'), ('Tony Marín', 'Marco Antonio Reátegui'), ('V Revelación de Jaén', ''),
('Grupo Impacto de Bellavista', 'Vicente Rengifo'), ('Cuarteto Imbatible', 'Julio César Mau Orlandini'), ('Julio Mau y su Cuarteto', 'Julio César Mau Orlandini');

