USE Cumbia_Peruana;

SELECT * FROM personas;

-- Insertar Directores (ordenados por importancia del grupo)
INSERT INTO personas (nombre, apodo)
VALUES
('Enrique Delgado Montes', ''),
('Abdón Marino Valencia Garay', ''),
('Jorge Rodríguez Grández', ''),
('Segundo Edilberto Cuestas Chacón', 'Beto'),
('Víctor Homero Casahuamán Marín', ''),
('Juan Wong Paredes', ''),
('Lorenzo Palacios Quispe', 'Chacalón'),
('Carlos Morales Sánchez', ''),
('Jaime Venturo Moreira Mercado', ''),
('Raúl Llerena Vásquez', 'Ranil'),
('Juan Alberto Maraví Chombo', ''),
('Víctor Horacio Casahuamán Bendezú', ''),
('Víctor Carrasco Tineo', 'Viko'),
('Federico Alberto Mauri Almonacid', 'Tito'),
('Ernesto Diestro Herrera', ''),
('Emerson Ruiz Mosquera', ''),
('Manuel Jorge Chávez Malaver', ''),
('Nelson Baltazar Canevello Pardo', ''),
('Augusto Paco Bernardillo Gutiérrez', ''),
('Rogelio Velásquez Pérez', ''),
('Efrén García Viena', ''),
('Teodoro Félix Arellano Fernández', ''),
('Lener Alejandro Muñoz Reyes', ''),
('Juan Campos Muñoz', 'El Chino'),
('Fernando Arias', ''),
('Juan Berardo Hernández Sánchez', 'Manzanita'),
('Jorge Chambergo Porta', ''),
('Alejandro Zárate Espinoza', ''),
('Tulio Trigozo Reátegui', ''),
('Josue Jurado Zurita', ''),
('José Luis Carballo Nunura', 'Mota'),
('Alfonso Escalante Quispe', 'Chacal'),
('Luis Florentino León Pariasca', 'Tino'),
('Leonardo Vela Rodríguez', ''),
('Walter Lozada Floriano', ''),
('José Manuel de la Cruz Oré', 'Tito'),
('Alejandro Torres Liza', ''),
('Walter León Aguilar', ''),
('Manuel Quiroga Querevalú', ''),
('Abelardo Gutiérrez Alanya', 'Tongo'),
('Alfonso Alejandro Morán Sirumbal', 'Claudio'),
('Pedro Gregorio López', 'Martín'),
('José Félix Martínez Romero', 'El Chévere'),
('Juan Miguel Arana Zumaeta', ''),
('Maximiliano Chávez Saavedra', ''),
('Óscar Sánchez Noriega', ''),
('Víctor Ramírez Raymundo', ''),
('Salomón Sánchez Saavedra', ''),
('Francisco Lema Vásquez', 'Pancho'),
('Ronald Ferreyra', ''),
('Américo Vilcatoma Aranda', ''),
('Rolando Vega Carranza', ''),
('Alejandro Grover Pacheco Mauricio', 'Alín'),
('Ricardo Portal', 'Richard'),
('Smith César Salazar Vila', ''),
('Miguel Ordinola Castillo', ''),
('Wilmer Elvin Salazar Vila', ''),
('Hernán Torres', ''),
('Luis Alejandro Ríos Villanueva', 'Lucho'),
('Saúl Casahuamán Fuertes', ''),
('Willy Alvarado', ''),
('Juan Manuel de la Cruz Oré', 'Mamita'),
('Leoncio Macedonio Sierra Santiago', ''),
('Leandro Uscamayta', ''),
('Abel Flores Ramírez', ''),
('Pedro Macavilca', ''),
('Segundo Guillermo Esqueche', 'Memo'),
('Fernando Cerrón Aguilar', ''),
('Alfonso Córdova Gonzáles', ''),
('Jesús Oswaldo Ortega Andrade', 'El Guajiro'),
('Próspero Alva', ''),
('Jorge Nolasco', ''),
('Óscar Zárate Carbajal', ''),
('Julio Jesús Risco Buitrón', ''),
('Juan Chávez Salazar', ''),
('Carlos Ramírez Centeno', 'El Patrón'),
('Aurelio Bayona Quiroga', ''),
('José María Yzazaga', 'Joselillo'),
('Héctor Enrique Bustamante Gómez', ''),
('Teófilo Antonio Baldeón Sosa', 'Filo'),
('Lucas Lázaro Machuca Mantilla', ''),
('Ciro Abraham Lezama Illescas', ''),
('Zenón Antonio Yabar Díaz', ''),
('Efraín Ochoa', ''),
('Quintín Palomino', ''),
('Héctor Manuel Farfán Canales', ''),
('Reynaldo Paitán', ''),
('Pedro Rojas', ''),
('Hugo Soto Ponce', ''),
('Anibal Ángel Rosado García', ''),
('Abraham Sánchez Pumacayo', ''),
('Félix Zuñiga', ''),
('Edgar Carlos Villarroel', ''),
('Romulo Navarro Meza', ''),
('Luis Seijas Peña', ''),
('Óscar Hidalgo Vargas', 'El Tocachino de Oro'),
('Vicente Gonzáles', ''),
('Moises Cruz Medina', ''),
('Enrique Canales Carbajo', ''),
('José Ramón Barrionuevo', ''),
('Carlos Vidal', ''),
('José Cerrón Canto', ''),
('Alcides de la Cruz Barra', ''),
('Víctor José Daza Ponte', ''),
('Andrés Vásquez Álvarez', 'Pumita Andy'),
('Moises Pérez P.', ''),
('Julio Garay Sosa', ''),
('Juan Quillatupa', ''),
('Eddy Ayala Pingo', ''),
('Inocencio Díaz Alvarado', ''),
('Arnaldo Tapia', ''),
('Julio Barzola Domínguez', ''),
('José Manuel Canela Martínez', ''),
('Armando Tomás Tames Jara', ''),
('Jorge Franco Prado', ''),
('Luis Nigro Sánchez', ''),
('Manuel Ángel Mantilla Paredes', ''),
('Pepe Vivanco Maita', ''),
('Juan Eduardo Rebaza Cárdenas', ''),
('Ricardo Valles Rodríguez', 'Kibe'),
('Tony Vásquez', ''),
('Dionisio Quispe', ''),
('José Luis Calderón', 'Riñón'),
('Roberto Suasnabar', ''),
('Javier Silva Humeres', ''),
('Juan Honorato Robles Quiñonez', ''),
('José Saturnino Salvatierra Espiza', ''),
('Nilo Juan Segura Obregón', ''),
('Ray Cuestas', ''),
('Kioshi Simamoto Tuesta', ''),
('Guillermo Ruiz Barahena', 'Toby'),
('Néstor Orlando Corpus Barrantes', ''),
('Víctor Asunción Chumpitaz Dupuy', ''),
('Carlos Urtecho', ''),
('Félix Sánchez Ponce', ''),
('Enrique Araujo', ''),
('Javier Ramos Choque', 'Manzana'),
('Freddy Roland', ''),
('Rubén Jara', ''),
('Alfredo Linares', ''),
('Humberto Yván Recoba Chávez', ''),
('Ricardo Manuel Oliver López', ''),
('Gilberto Félix Tasayco', ''),
('Hernán Rodríguez Haro', ''),
('Juan Alarcón Malvaceda', ''),
('Gerardo Jaimes Soto', ''),
('Teddy Navarro', ''),
('Manuel Ticerán Vela', ''),
('César Augusto Calderón López', 'Chechar'),
('César Mortola Aburto', ''),
('Pascual Matos Arteaga', 'El Tigrillo'),
('Julio César Mau Orlandini', ''),
('César Alvarado B.', ''),
('Jorge Reyes Solsol Miranda', ''),
('Fernando Gambini', ''),
('Manuel Cajavilca Morales', ''),
('Hildebrando Bejarano Díaz', ''),
('Gonzalo Chávez', ''),
('Agustín Flores', ''),
('Fortunato Calderón', ''),
('Raúl Ríos Guevara', 'Samuray'),
('Estel Malpartida', ''),
('Hugo Pinedo Avila', ''),
('Max Trujillo', ''),
('Pascual López', ''),
('Teófilo Moreno Ch.', ''),
('Alberto Amorós Cortijo', 'Rocky'),
('Filiberto Vivas', ''),
('Francisco Vela T.', ''),
('Crisanto Espinoza', ''),
('Luis Abanto Valdeiglesias', ''),
('Carlos Barrios Ayllón', ''),
('César Baltazar Julcarim', ''),
('Jesús Valentín Uchalin', ''),
('Juan Salazar Cruz', ''),
('Raúl Alegría', ''),
('Juan Minches Campos', ''),
('Orestes de La Torre', ''),
('Teodoro Sánchez C.', ''),
('Carlos Godoy', ''),
('José Vicente', ''),
('Wilfredo Meza H.', ''),
('Jhon Arana', ''),
('Raúl A. Bastidas S.', ''),
('Antonio Gutierrez', ''),
('Arturo Velásquez Reynoso', 'Panetón'),
('Nicanor Bedriñana Morales', 'Panamito'),
('Luis Guevara', ''),
('Carlos Cheng Palomino', ''),
('Horacio Gómez Aragón', ''),
('Esteban Aguilar', 'Shishako'),
('Flavio Vicente Quispe', ''),
('Augusto de La Cruz', ''),
('Manuel Antonio Chuque Silva', ''),
('Rodolfo Mantari', ''),
('Jorge Calatayud Olivares', ''),
('Juan Ricardo Hinostroza Jara', 'Papita'),
('Hugo Casahuamán Fuertes', ''),
('Alberto León Romero', ''),
('Jesús Meza', ''),
('Jorge Esquivel Z.', ''),
('Manuel Navarro', ''),
('Daniel Jacinto Moreno', ''),
('Jorge Durand Tovar', ''),
('Pedro Máximo Egas Sáenz', ''),
('Arnaldo Clemente', ''),
('Fernando García', ''),
('Hugo Walas', ''),
('Néstor Iván Quispe Sayritupac', ''),
('Hermanos Paredes', ''),
('Ernesto Pomayala', ''),
('José Ninapaitán Huayta', 'Pepito Quechua'),
('Alejandro Novoa Cruz', 'Piraña'),
('Narciso Quispe Huasco', ''),
('Zócimo Ramírez', ''),
('José Hernández Morales', ''),
('Ygor López Ríos', ''),
('Mauro García Pastor', ''),
('Alfredo Henríquez Paz', ''),
('Luis López Torres', ''),
('Fidenciano Buendia Hinostroza', ''),
('Máximo Camacho Ruiz', ''),
('Pablo Inca', ''),
('Carlos Romero', ''),
('Raúl Herrera', ''),
('Daniel Huapaya Flores', ''),
('Jorge Hurtado', ''),
('Rolando Hilario', ''),
('Carlos Hervacio A.', ''),
('Jaime García', ''),
('Milton Andina', ''),
('Mariano Ignacio Aliaga Peña', 'Camote'),
('José Gómez Valdivia', ''),
('Manuel Samaniego', ''),
('Basilio Pedro de la Cruz Fernández', ''),
('Éver Lizárraga', ''),
('Sixto Mendoza Ríos', ''),
('Tito Aybar C.', ''),
('Zócimo Cueva Armas', ''),
('Abdón Pucuhuayla S.', ''),
('Diomedes Rufino Riveros Guzman', ''),
('Dionisio Palomino Díaz', ''),
('Walter Puente R.', ''),
('Leoncio Maldonado', ''),
('Waldo Chipana', ''),
('Reyes Salazar', ''),
('Eleazar Cárdenas', ''),
('George Závaleta', ''),
('Américo Quicaña', ''),
('Fernando Díaz Loli', ''),
('Víctor Arturo Barrientos Vásquez', ''),
('Luis Escalante', ''),
('Hector Chacón', ''),
('Fredy Velasco Meza', ''),
('Manuel Jesús Llanos', ''),
('Fernando Jeri R.', ''),
('Carlos Tovar B.', ''),
('Johnny Arce', ''),
('Demetrio Caycho Champac', ''),
('Anibal Sebastián Aliaga Madueno', ''),
('Guillermo Miranda', ''),
('William Franklin Salazar Vila', ''),
('César Cárdenas R.', ''),
('Fernando Limo', ''),
('Alfredo González Chávez', ''),
('Daniel Ávalos', ''),
('José Escalante Quispe', 'Chacalito'),
('Roberto Rivera Pizarro', ''),
('Juan Zevallos', ''),
('Raúl Ortiz Sánchez', ''),
('Francisco Izquierdo V.', ''),
('José Luis Carrizales', ''),
('Luis R. Garagatti A.', ''),
('Moisés Castellares Huamaní', ''),
('Koko Arias', ''),
('Ricardo Córdova Cárdenas', ''),
('Orlando Laopa', ''),
('Antonio Raúl Basurto Valenzuela', ''),
('Noeir Gaspar A.', ''),
('Jorge Huamalí', ''),
('Juan Cahuama Valenzuela', ''),
('Juan Chuquín Beltrán', ''),
('Sulma Nieto', ''),
('Luis Gonzáles Vigil', ''),
('Jorge Ramírez', ''),
('Justiniano Sánchez M.', ''),
('Menandro Alarcón Solano', ''),
('Daniel Mogollón Bravo', ''),
('Alejandro Ludeña Díaz', ''),
('Carlos Salvatierra', ''),
('Antonio Rodríguez', ''),
('Alejandro Agustín Cáceres Perea', 'Cholín'),
('Demis Celis Pando', ''),
('Flavio Vicente', ''),
('Daniel Acuña', ''),
('Fernando Pacheco Serrano', ''),
('Juan Valentino', ''),
('Gabriel Muñoz', ''),
('Román Prado Vásquez', ''),
('Henry Figueroa', ''),
('Alfredo Durand García', ''),
('Andrés de Colbert', ''),
('Adrián Flores Huarachi', ''),
('Juan García Salazar', ''),
('Fernando Quesada', ''),
('Raúl Lara', ''),
('Teodoro Laura Amao', 'Teo'),
('José Luis Alva Lezcano', ''),
('Rolando Wilmer', ''),
('Carlos Palomino', ''),
('Hermanos Montalvo', ''),
('Juan Gutiérrez', ''),
('Julio Morales H.', ''),
('José López', ''),
('Marcelo Aguirre', ''),
('Cosme Flores C.', ''),
('Julio Ríos', ''),
('Carlos Ruiz K.', ''),
('Luis Carrasco Tineo', ''),
('Eduardo Pizarro P.', ''),
('Abel Berrospi G.', ''),
('Juan Benigno Tapia', ''),
('Isaac Sánchez Gonzáles', ''),
('Alberto Mendieta', ''),
('Humberto Caycho Alcantara', 'Tito'),
('Diomedes Ureta', ''),
('Arturo Garate Salva', ''),
('Remigio Cuba', ''),
('W. Miranda Cámara', ''),
('Félix Vargas', ''),
('Oscar Galindo', ''),
('Gilberto Torres', ''),
('Alberto Zárate', ''),
('César Garay', ''),
('Luis Sánchez', ''),
('Freddy Velasco Meza', 'Pañuelito'),
('Tito Perez', ''),
('Wilfredo Mendoza', ''),
('Augusto Lucho Laverde', ''),
('Eduardo Chachi M.', ''),
('Jorge Ramírez V.', ''),
('Jorge Oliver Bernable', ''),
('Wilber Peña', ''),
('Javier Chacha Quiquia', ''),
('Marino Hinostroza', ''),
('Armando Lizana T.', ''),
('César Zavala Maldonado', ''),
('Aniceto Salazar', ''),
('Francisco Cuñas', ''),
('Jesús Neyra', ''),
('Isaías Cotos Solís', ''),
('José Lorenzo Alván Bardales', ''),
('Mario Egúsquiza', ''),
('Nesito Palomino Pedrosoca', ''),
('Pascual Coronado Capcha', 'Pascualillo'),
('Williams Alanya Ramírez', ''),
('Marco Antonio Reátegui Marín', 'Tony'),
('Víctor Yaipén Uypán', ""),
('Lizardo Paolo', ""),
('Eusebio Pérez Campojo', "");