-- Insertando SELLOS ###
INSERT INTO sellos_discograficos (nombre_sello) 
VALUES

('Infopesa'), ('Horóscopo'), ('Sonoradio'), ('Odeón'), ('Midas'),
('FTA'), ('Music Shop'), ('Prodisar'), ('Caravana Record'), ('Volcán'),
('Difa'), ('Universal'), ('Caracol'), ('Disgonza'), ('Dinsa'),
('Do Re Mi'), ('Colibrí'), ('Producciones Markahuasi'), ('Bambú'), ('Prod Music'),
('Coladisa'), ('Faro Records'), ('Gloria'), ('MAG'), ('Discope'),
('Rey Record'), ('Fono Video'), ('Virrey'), ('Sonata'), ('Discos Chicha'),
('Arco Iris'), ('Rocio'), ('Rosa Record'), ('Decibel'), ('Dispasa'),
('Iempsa'), ('Poderoso'), ('Imsa'), ('Trebol Record'), ('Dilama'),
('Disco Ramírez'), ('Fonovideo'), ('CBS'), ('Pemo'), ('Delta Discos'),
('Onix'), ('Cadillo'), ('Estrella Record'), ('Prodic'), ('Disco Lindo'),
('Fonohit'), ('Fadisa'), ('Clase'), ('LESISA'), ('Universo'),
('Walter Rodríguez'), ('Edicsa'), ('Fonografica Machu Picchu'), ('Primicia'), ('Sideral'),
('America'), ('Emucel'), ('Fonolux'), ('Gama'), ('OCSA'),
('Sono Hit Records'), ('Amauta'), ('Galem'), ('Gran Prix'), ('Ollanta'),
('Palomino'), ('Pentafono'), ('Prosesa'), ('Santa Fe'), ('Solitario'),
('Discos Yolita'), ('Co Di Sa'), ('Difaza'), ('Disco Mar'), ('Discos Litoral'),
('Hispano'), ('Mar'), ('Music Hits'), ('Prodita'), ('Titan'),
('Angelito'), ('Discos Flower'), ('Lady Vanessa'), ('Pantel'), ('Peruvox'),
('Virgo'), ('American Record'), ('Avispa'), ('Din-Don'), ('Discos del Puerto'),
('Doxa'), ('Edinha'), ('Escorpio'), ('Flavidiscos'), ('Discos Hormiga'),
('Impacto'), ('Inka Perú'), ('JNC'), ('KDT'), ('Kozmoz'),
('Producciones Llerena'), ('Maravilla'), ('Proa'), ('Profoqsa'), ('PSA'),
('Rueda'), ('ADG'), ('Lucero'), ('Ifemsa'), ('Kastorcito'),
('Sucesos'), ('A.G.A'), ('Abdon'), ('Almersa'), ('Analog Africa'),
('Auray'), ('Barmi'), ('Canpard'), ('Constelación'), ('Discos Continental'),
('Dialsa'), ('Digsa Records'), ('Direysa'), ('Discos Alta Tensión'), ('Discos Bahía'),
('Discos Estelar'), ('Discos Izquierdo'), ('Discos Jesús'), ('Discos Jhim'), ('Discos Kanuta'),
('Discos Luz'), ('Discos Mezcla'), ('Discos Mida'), ('Discos Plateado'), ('Discos Revelación'),
('Discos Selva'), ('Discos Universal'), ('Discos Vanidad'), ('Discos Vision'), ('Eralba'),
('Producciones Escorpión'), ('Exdels'), ('FBHSA'), ('Fomusa'), ('Foneco'),
('Inca Record'), ('Indisa'), ('Infomusa'), ('Inprofoleon'), ('Jairot'),
('Limon Records'), ('Litoral'), ('LUX'), ('Maribel'), ('Mas Record'),
('Miel Record'), ('Milagros'), ('Nazca Chavin'), ('ORO'), ('Orquidea Record'),
('Pa Records'), ('Pacifico'), ('Pato Record'), ('Piscis'), ('Polydor'),
('PPTQ'), ('Prod Leo'), ('Prodinsa Lima'), ('Prodisa'), ('Discos Prodpisa'),
('Prohisa'), ('Prolama'), ('Promarisa'), ('Pueblo'), ('RBM'),
('RCA'), ('RG'), ('RSD'), ('Santa Cecilia'), ('Selva Record'),
('Sol Disco'), ('Sonido Tuesna'), ('Tauro'), ('Top Hits'), ('Yaba'),
('Casino'), ('Producciones Cristal'), ('Discos Huancayo'), ('Discos Oliver'), ('Ifaza'),
('Loretano'), ('Mary Yessy'), ('Profana'), ('Rado'), ('Solinka'),
('Venus'), ('Cocodrilo'), ('Promusen'), ('Ninsa'), ('Kozmoz'),
('Ecodiscos'), ('Producciones Walter León'), ('Huatisa'), ('Genesis'), ('Producciones EBC Record'),
('FIPSA'), ('Cantarito Rojo'), ('Discos Santa Rosa'), ('JEMM'), ('DINO'),
('Guiceso'), ('Impesa Records'), ('Dicha'), ('Colonia'), ('Catalina Huanca'),
('Promusur'), ('Discos Coopersa'), ('Superhit'), ('Gesa Reckords'), ('NRC'),
('Discos Coral'), ('Aurora Records'), ('F.M'), ('Geranio Record'), ('Panorama'),
('Parosa'), ('Magia'), ('Edy Samber S.A'), ('BEHERSA'), ('Chisa'),
('Comul'), ('Salsa'), ('Almeri'), ('DISA Records'), ('Alteza Records'),
('El Chancayano'), ('CV Records'), ('Hernan Torres'), ('Lider'), ('SFA'),
('Proesa'), ('Rosita Producciones'), ('TAMA S.A'), ('Producciones ELSI'), ('Producciones Hollywood'),
('Kantaro Records'), ('Producciones Taurus'), ('Producciones DALMA'), ('Promociones O.C.S.A'), ('Producciones Ovnis'),
('Producciones Javak'), ('Producciones Vanessa'), ('Producciones Fonograficas Maravilla');
